### ISSUE TITLE
Maven install does not work for Speech2text sample App.java

### ISSUE THREAD

**Issue by jeremykong-ur** [somahota/Speech-Based-Code-Editor-Project#1]
Now I could only run it within eclipse, but not as a jar.
I think it has something to do with dependencies in pom.xml.

**Comment by Rashi1997** [comment]
@jeremykong-ur this is fixed in the latest commit Can you also test it?

**Comment by jeremykong-ur** [comment]
What command did you use?
I tried `mvn clean install` and it still does not work.

$ java -jar voice2text-0.0.1-SNAPSHOT.jar 
Error: Unable to initialize main class edu.brown.cs.voice2text.App
Caused by: java.lang.NoClassDefFoundError: com/google/api/gax/rpc/ResponseObserver.

emmmmmm

**Comment by Rashi1997** [comment]
1.  make sure your pom.xml has the new plugin for jar-dependencies
2. you can do a mvn install inside eclipse by right-clicking on project name Run As>Maven Install
3. there will be a jar file in the target folder, so cd to the target folder
4. run this command inside target `GOOGLE_APPLICATION_CREDENTIALS=~/Downloads/speech2code-293021-9e5a1a5ad9b0.json java -jar voice2text-0.0.1-SNAPSHOT-jar-with-dependencies.jar`

**Comment by jeremykong-ur** [comment]
Emm,
If I run `mvn assembly:assembly -DdescriptorId=jar-with-dependencies`, I can get it to work.
Your pom file seems fine, not sure why it's not automatically applied.

I will close the issue since at least there is a work around.
